version: 2
jobs:

  build:
    docker:
      - image: openfaas/faas-cli:0.6.9
    steps:
      - checkout
      - setup_remote_docker: {docker_layer_caching: true}
      - run:
          name: Build
          command: ./faas-cli build -f fninfo.yml

  deploy:
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker: {docker_layer_caching: true}
      - run:
          name: Push
          command: |
            if [[ -z "${CIRCLE_PULL_REQUEST}" ]] && [[ "${CIRCLE_PROJECT_USERNAME}" = "stefanprodan" ]] ; then
              echo $REGISTRY_PASSWORD | docker login --username $REGISTRY_USERNAME --password-stdin
              docker tag stefanprodan/fninfo:latest stefanprodan/fninfo:${CIRCLE_SHA1}
              docker push stefanprodan/fninfo:${CIRCLE_SHA1}
              docker push stefanprodan/fninfo:latest
            else
              echo "Do not push image"
            fi

workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires: [build]
          filters:
            branches: {only: [master]}
