version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Install OpenFaaS CLI
          command: make cli
      - run:
          name: Build function
          command: make build
      - run:
          name: Push function to registry
          command: |
            if [[ -z "${CIRCLE_PULL_REQUEST}" ]] && [[ "${CIRCLE_PROJECT_USERNAME}" = "stefanprodan" ]] ; then
              echo $REGISTRY_PASSWORD | docker login --username $REGISTRY_USERNAME --password-stdin
              make push
            else
              echo "Do not push image"
            fi

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches: {only: [master]}
