version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Install OpenFaaS CLI
          command: make cli
      - run:
          name: Build function
          command: make build
      - run:
          name: Push master to registry
          command: |
            if [[ -z "${CIRCLE_PULL_REQUEST}" ]] && [[ -z "${CIRCLE_TAG}" ]] && [[ "${CIRCLE_PROJECT_USERNAME}" = "stefanprodan" ]] ; then
              echo $REGISTRY_PASSWORD | docker login --username $REGISTRY_USERNAME --password-stdin
              make push
            else
              echo "Do not push image"
            fi
      - run:
          name: Push tag to registry
          command: |
            if echo "${CIRCLE_TAG}" | grep -Eq "^[0-9]+(\.[0-9]+)*(-[a-z]+)?$"; then
              echo $REGISTRY_PASSWORD | docker login --username $REGISTRY_USERNAME --password-stdin
              docker tag stefanprodan/fninfo:latest stefanprodan/fninfo:${CIRCLE_TAG}
              docker push stefanprodan/fninfo:${CIRCLE_TAG}
            else
              echo "Do not push image"
            fi

workflows:
  version: 2
  main:
    jobs:
      - deploy
